server:
    port: 11111

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
     #关闭自我保护（开发环境）
    instance:
        leaseRenewalIntervalInSeconds: 1
        leaseExpirationDurationInSeconds: 2

spring:
    application:
        name: notice
    datasource:
        name: test
        url: jdbc:mysql://localhost:3306/notice?useUnicode=true&amp;characterEncoding=UTF-8
        username: root
        password:
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20


mybatis:
    mapper-locations: classpath:mapping/*.xml
    type-aliases-package: com.entity

aliyun:
    sms:
        accessKeyId:
        accessKeySecret:
        #短信签名
        signNamerom: 综合运维云平台
        #短信模板代码
        templateCode: SMS_144940201

weixin:
    secret:
    corpId:
    agentid:

mail:
    host: smtp.163.com
    port: 465
    #host: smtp.163.com
    #port: 25
    user:
    password:

#系统应用配置
userConfig:
    #阻塞队列长度
    queueLength: 60
    #线程池大小
    executorLength: 30